/**
 * Codegen — writes src/data/catalog.generated.ts from the per-language data files.
 *
 * Emits two things, both derived from the data files (single source of truth):
 *   · `catalog`  — the lightweight metadata (id/name/category/popularity/accent/
 *                  extensions) the sidebar + router need for EVERY language, so the
 *                  entry bundle carries only that, not the heavy annotations/examples.
 *   · `loaders`  — id → dynamic import() of the FULL LanguageDef, one chunk each,
 *                  pulled on demand when a language is selected.
 *
 * Re-run after adding or changing a language: `bun run gen:catalog` (also runs
 * automatically at the start of `bun run build`).
 */
import { readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import type { LanguageDef } from '../src/lib/types'

const DATA_DIR = join(import.meta.dir, '..', 'src', 'data')
const OUT = join(DATA_DIR, 'catalog.generated.ts')
const SKIP = new Set(['index.ts', 'comingSoon.ts', 'catalog.generated.ts'])

const files = readdirSync(DATA_DIR)
  .filter((f) => f.endsWith('.ts') && !SKIP.has(f))
  .sort()

type Entry = { id: string; exportName: string; file: string; def: LanguageDef }
const entries: Entry[] = []

for (const file of files) {
  const mod = (await import(pathToFileURL(join(DATA_DIR, file)).href)) as Record<string, unknown>
  const named = Object.entries(mod).find(
    ([, v]) => v != null && typeof v === 'object' && 'id' in (v as object),
  )
  if (!named) throw new Error(`gen-catalog: ${file} has no LanguageDef export`)
  const [exportName, def] = named as [string, LanguageDef]
  entries.push({ id: def.id, exportName, file: file.replace(/\.ts$/, ''), def })
}

// Fail loudly on duplicate ids — they'd silently shadow each other in the loader map.
const seen = new Set<string>()
for (const e of entries) {
  if (seen.has(e.id)) throw new Error(`gen-catalog: duplicate language id "${e.id}"`)
  seen.add(e.id)
}

function metaLiteral(def: LanguageDef): string {
  const meta: Record<string, unknown> = {
    id: def.id,
    name: def.name,
    category: def.category ?? 'language',
    accentHex: def.accentHex,
    extensions: def.extensions,
  }
  if (def.popularity !== undefined) meta.popularity = def.popularity
  return JSON.stringify(meta)
}

const catalogLines = entries.map((e) => `  ${metaLiteral(e.def)},`).join('\n')
const loaderLines = entries
  .map(
    (e) => `  ${JSON.stringify(e.id)}: () => import('./${e.file}').then((m) => m.${e.exportName}),`,
  )
  .join('\n')

const out = `// AUTO-GENERATED by scripts/gen-catalog.ts — DO NOT EDIT BY HAND.
// Run \`bun run gen:catalog\` after adding or changing a language in src/data/.
import type { LanguageDef, LanguageMeta } from '../lib/types'

/** Lightweight metadata for every language/concept — enough for the sidebar and route
 *  validation, WITHOUT the heavy annotations/examples (those load via \`loaders\` below). */
export const catalog: LanguageMeta[] = [
${catalogLines}
]

/** id -> lazy import of the FULL LanguageDef (its own chunk, loaded on selection). */
export const loaders: Record<string, () => Promise<LanguageDef>> = {
${loaderLines}
}
`

writeFileSync(OUT, out)
console.log(`✓ catalog.generated.ts — ${entries.length} entries`)
